name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  create-draft-release:
    name: Automated semantic versioned draft release
    runs-on: self-hosted
    steps:
      - name: Create semver tag from PR labels
        id: semver
        uses: timperman/semver-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_strategy: none
          tag_format: 'v%major%.%minor%.%patch%'
      
  build:
    runs-on: ubuntu-latest
    needs: ["setup-environment"]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
