name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup-environment:
    runs-on: [self-hosted, X64, Linux]
    steps:
    - name: Setup environemnt variables for build job
      run: export APP_ENV="1.0.0"
  build:
    runs-on: [self-hosted, X64, Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
